apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pv-claim-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
